import { Album, ChartAlbum, UpcomingAlbum } from "./types";

// 단순한 placeholder - 네트워크 없이 즉시 로딩
const placeholder =
  "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMzAwIiBoZWlnaHQ9IjMwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KICA8cmVjdCB3aWR0aD0iMzAwIiBoZWlnaHQ9IjMwMCIgZmlsbD0iIzEyMzQ1OCIvPgogIDx0ZXh0IHg9IjE1MCIgeT0iMTUwIiBmb250LWZhbWlseT0iQXJpYWwsIHNhbnMtc2VyaWYiIGZvbnQtc2l6ZT0iMjQiIAogICAgICAgIGZpbGw9IndoaXRlIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBkb21pbmFudC1iYXNlbGluZT0ibWlkZGxlIj5BTEJVTTwvdGV4dD4KICA8L3N2Zz4K";

// 최신 앨범 데이터
export const newAlbums: Album[] = [
  {
    id: 1,
    title: "새벽에 듣는 음악",
    artist: "아이유",
    cover: placeholder,
    price: "25,000원",
  },
  {
    id: 2,
    title: "Butter",
    artist: "BTS",
    cover: placeholder,
    price: "23,500원",
  },
  {
    id: 3,
    title: "The Album",
    artist: "BLACKPINK",
    cover: placeholder,
    price: "22,000원",
  },
  {
    id: 4,
    title: "Bad Decisions",
    artist: "Benny Blanco, BTS",
    cover: placeholder,
    price: "19,800원",
  },
  {
    id: 5,
    title: "Proof",
    artist: "BTS",
    cover: placeholder,
    price: "35,000원",
  },
  {
    id: 6,
    title: "LALISA",
    artist: "LISA",
    cover: placeholder,
    price: "21,000원",
  },
  {
    id: 7,
    title: "BORN PINK",
    artist: "BLACKPINK",
    cover: placeholder,
    price: "27,500원",
  },
  {
    id: 8,
    title: "NewJeans",
    artist: "NewJeans",
    cover: placeholder,
    price: "18,500원",
  },
  {
    id: 9,
    title: "DIMENSION : ANSWER",
    artist: "ENHYPEN",
    cover: placeholder,
    price: "24,000원",
  },
  {
    id: 10,
    title: "LOVE DIVE",
    artist: "IVE",
    cover: placeholder,
    price: "19,500원",
  },
];

// 차트 데이터
export const chartAlbums = {
  realtime: [
    {
      id: 1,
      title: "Dynamite",
      artist: "BTS",
      cover: placeholder,
      rank: 1,
      price: "18,000원",
    },
    {
      id: 2,
      title: "Pink Venom",
      artist: "BLACKPINK",
      cover: placeholder,
      rank: 2,
      price: "20,000원",
    },
    {
      id: 3,
      title: "After LIKE",
      artist: "IVE",
      cover: placeholder,
      rank: 3,
      price: "17,500원",
    },
    {
      id: 4,
      title: "ANTIFRAGILE",
      artist: "LE SSERAFIM",
      cover: placeholder,
      rank: 4,
      price: "19,000원",
    },
    {
      id: 5,
      title: "Shut Down",
      artist: "BLACKPINK",
      cover: placeholder,
      rank: 5,
      price: "21,000원",
    },
    {
      id: 6,
      title: "FOREVER 1",
      artist: "소녀시대",
      cover: placeholder,
      rank: 6,
      price: "18,500원",
    },
    {
      id: 7,
      title: "Attention",
      artist: "NewJeans",
      cover: placeholder,
      rank: 7,
      price: "16,000원",
    },
    {
      id: 8,
      title: "LOVE DIVE",
      artist: "IVE",
      cover: placeholder,
      rank: 8,
      price: "17,000원",
    },
    {
      id: 9,
      title: "Talk that Talk",
      artist: "TWICE",
      cover: placeholder,
      rank: 9,
      price: "19,500원",
    },
    {
      id: 10,
      title: "Hype Boy",
      artist: "NewJeans",
      cover: placeholder,
      rank: 10,
      price: "16,500원",
    },
  ] as ChartAlbum[],

  korean: [
    {
      id: 1,
      title: "Ditto",
      artist: "NewJeans",
      cover: placeholder,
      rank: 1,
      price: "19,000원",
    },
    {
      id: 2,
      title: "사건의 지평선",
      artist: "윤하",
      cover: placeholder,
      rank: 2,
      price: "18,000원",
    },
    {
      id: 3,
      title: "Rush Hour",
      artist: "Crush, j-hope",
      cover: placeholder,
      rank: 3,
      price: "17,000원",
    },
    {
      id: 4,
      title: "ELEVEN",
      artist: "IVE",
      cover: placeholder,
      rank: 4,
      price: "18,500원",
    },
    {
      id: 5,
      title: "Nxde",
      artist: "(여자)아이들",
      cover: placeholder,
      rank: 5,
      price: "19,500원",
    },
    {
      id: 6,
      title: "TOMBOY",
      artist: "(여자)아이들",
      cover: placeholder,
      rank: 6,
      price: "17,500원",
    },
    {
      id: 7,
      title: "Cookie",
      artist: "NewJeans",
      cover: placeholder,
      rank: 7,
      price: "16,500원",
    },
    {
      id: 8,
      title: "Monologue",
      artist: "테이",
      cover: placeholder,
      rank: 8,
      price: "15,000원",
    },
    {
      id: 9,
      title: "사랑은 늘 도망가",
      artist: "임영웅",
      cover: placeholder,
      rank: 9,
      price: "16,000원",
    },
    {
      id: 10,
      title: "그라데이션",
      artist: "10CM",
      cover: placeholder,
      rank: 10,
      price: "15,500원",
    },
  ] as ChartAlbum[],

  international: [
    {
      id: 1,
      title: "As It Was",
      artist: "Harry Styles",
      cover: placeholder,
      rank: 1,
      price: "29,000원",
    },
    {
      id: 2,
      title: "Unholy",
      artist: "Sam Smith, Kim Petras",
      cover: placeholder,
      rank: 2,
      price: "28,000원",
    },
    {
      id: 3,
      title: "Anti-Hero",
      artist: "Taylor Swift",
      cover: placeholder,
      rank: 3,
      price: "27,000원",
    },
    {
      id: 4,
      title: "I'm Good (Blue)",
      artist: "David Guetta, Bebe Rexha",
      cover: placeholder,
      rank: 4,
      price: "26,000원",
    },
    {
      id: 5,
      title: "Bad Habit",
      artist: "Steve Lacy",
      cover: placeholder,
      rank: 5,
      price: "25,000원",
    },
    {
      id: 6,
      title: "Lift Me Up",
      artist: "Rihanna",
      cover: placeholder,
      rank: 6,
      price: "29,500원",
    },
    {
      id: 7,
      title: "Made You Look",
      artist: "Meghan Trainor",
      cover: placeholder,
      rank: 7,
      price: "24,000원",
    },
    {
      id: 8,
      title: "Lavender Haze",
      artist: "Taylor Swift",
      cover: placeholder,
      rank: 8,
      price: "27,500원",
    },
    {
      id: 9,
      title: "Calm Down",
      artist: "Rema, Selena Gomez",
      cover: placeholder,
      rank: 9,
      price: "23,500원",
    },
    {
      id: 10,
      title: "Snap",
      artist: "Rosa Linn",
      cover: placeholder,
      rank: 10,
      price: "22,000원",
    },
  ] as ChartAlbum[],
};

// 출시 예정 앨범 데이터
export const upcomingAlbums: UpcomingAlbum[] = [
  {
    id: 1,
    title: "새 앨범",
    artist: "레드벨벳",
    cover: placeholder,
    releaseDate: "2025-11-25",
    price: "22,000원",
  },
  {
    id: 2,
    title: "The New Chapter",
    artist: "NCT",
    cover: placeholder,
    releaseDate: "2025-12-01",
    price: "23,500원",
  },
  {
    id: 3,
    title: "Second Wind",
    artist: "Stray Kids",
    cover: placeholder,
    releaseDate: "2025-12-10",
    price: "24,500원",
  },
  {
    id: 4,
    title: "Breaking Point",
    artist: "ENHYPEN",
    cover: placeholder,
    releaseDate: "2025-12-15",
    price: "21,000원",
  },
  {
    id: 5,
    title: "New Era",
    artist: "SEVENTEEN",
    cover: placeholder,
    releaseDate: "2025-12-20",
    price: "26,000원",
  },
  {
    id: 6,
    title: "미래의 빛",
    artist: "아이유",
    cover: placeholder,
    releaseDate: "2026-01-05",
    price: "25,500원",
  },
  {
    id: 7,
    title: "Renaissance",
    artist: "TWICE",
    cover: placeholder,
    releaseDate: "2026-01-15",
    price: "24,000원",
  },
  {
    id: 8,
    title: "Next Level Up",
    artist: "aespa",
    cover: placeholder,
    releaseDate: "2026-01-25",
    price: "23,000원",
  },
];
